connection: &connection
  adapter: postgresql
  database: diariodailha_development
  pool: 5
  username: derik

development:
  <<: *connection
  database: diariodailha_development


test:
  <<: *connection
  database: diariodailha_development

# production:
#   adapter: postgresql
#   url: ENV['DATABASE_URL']

